<div class="theme-box page-item sort-bar">
    <div class="dropdown" tabindex="0">
        <div class="dropdown-btn"> Date &nbsp▼ </div>
        <ul class="dropdown-cont">
            <li class="dropdown-item"> Today </li>
            <li class="dropdown-item"> Week </li>
            <li class="dropdown-item"> Month </li>
            <li class="dropdown-item"> Year </li>
            <li class="dropdown-item"> All </li>
        </ul>
    </div>
    <div class="dropdown" tabindex="0">
        <div class="dropdown-btn"> Sort &nbsp▼ </div>
        <ul class="dropdown-cont">
            <li class="dropdown-item"> Likes </li>
            <li class="dropdown-item"> Replies </li>
        </ul>
    </div>
</div>
