<?php
$title = "Login";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box auth-box block-middle">
    <div class="main-title auth-title"> Login to Your Account </div>
    <div class="auth-section">
        <input class="main-input auth-input block-middle" placeholder="username">
        <input class="main-input auth-input block-middle" type="password" placeholder="password">
    </div>
    <div class="auth-info-text-cont">
        <a class="auth-info-text" href="/?url=signup"> Create a new account </a>
        <a class="auth-info-text" href="/?url=password/reset"> Forgot password? </a>
    </div>
    <button class="main-button auth-button" type="submit" name="button"> Login </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
