<?php
$title = "Password Reset";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box card-box block-middle">
    <div class="main-title card-title"> Password Reset </div>
    <div class="card-section">
        <input class="main-input card-input block-middle" type="email" placeholder="email">
        <input class="main-input card-input block-middle" type="password" placeholder="new password">
        <input class="main-input card-input block-middle" type="password" placeholder="new password (repeat)">
    </div>
    <button class="main-button card-button" type="submit" name="button"> Send Verification </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
