<?php
$title = "Password Verify";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box card-box block-middle">
    <div class="main-title card-title"> Password Verify </div>
    <div class="card-section">
        <input class="main-input card-input block-middle" type="password" placeholder="password">
        <input class="main-input card-input block-middle" type="password" placeholder="password (repeat)">
    </div>
    <button class="main-button card-button" type="submit" name="button"> Submit </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
