<?php
$title = "Password Reset";
include_once LAYOUTS . "header.phtml"; ?>

<div class="theme-box auth-box block-middle">
    <div class="auth-title"> Password Reset </div>
    <div class="auth-section">
        <input class="main-input auth-input block-middle" type="email" placeholder="email">
        <input class="main-input auth-input block-middle" type="email" placeholder="email (repeat)">
    </div>
    <button class="main-button auth-button" type="submit" name="button"> Submit </button>
</div>

<?php include_once LAYOUTS . "footer.phtml";
