<?php
$title = "Password Reset";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box auth-box block-middle">
    <div class="main-title auth-title"> Password Reset </div>
    <div class="auth-section">
        <input class="main-input auth-input block-middle" type="email" placeholder="email">
    </div>
    <button class="main-button auth-button" type="submit" name="button"> Send Verification </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
