<?php
$title = "Password Verify";
include_once LAYOUTS . "header.phtml"; ?>

<div class="theme-box auth-box block-middle">
    <div class="auth-title"> Password Verify </div>
    <div class="auth-section">
        <input class="main-input auth-input block-middle" type="password" placeholder="password">
        <input class="main-input auth-input block-middle" type="password" placeholder="password (repeat)">
    </div>
    <button class="main-button auth-button" type="submit" name="button"> Submit </button>
</div>

<?php include_once LAYOUTS . "footer.phtml";
