<?php
$title = "Signup";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box auth-box block-middle">
    <div class="main-title auth-title"> Create a New Account </div>
    <div class="auth-section">
        <input class="main-input auth-input block-middle" placeholder="username">
        <input class="main-input auth-input block-middle" type="email" placeholder="email">
        <input class="main-input auth-input block-middle" type="password" placeholder="password">
        <input class="main-input auth-input block-middle" type="password" placeholder="password (repeat)">
    </div>
    <button class="main-button auth-button" type="submit" name="button"> Signup </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
