<?php
$title = "Signup";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box card-box block-middle">
    <div class="main-title card-title"> Create a New Account </div>
    <div class="card-cont">
        <input class="main-input card-input block-middle" placeholder="username">
        <input class="main-input card-input block-middle" type="email" placeholder="email">
        <input class="main-input card-input block-middle" type="password" placeholder="password">
        <input class="main-input card-input block-middle" type="password" placeholder="password (repeat)">
    </div>
    <button class="main-button card-button" type="submit" name="button"> Signup </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
