<?php
$title = "Post";
include_once LAYOUTS . "header_main.phtml";

include_once VIEWS . "post" . DIRECTORY_SEPARATOR . "post_box.phtml";
include_once VIEWS . "comment" . DIRECTORY_SEPARATOR . "comment_sort_bar.phtml";
include_once VIEWS . "comment" . DIRECTORY_SEPARATOR . "comment_input.phtml";
include VIEWS . "comment" . DIRECTORY_SEPARATOR . "comment_box.phtml";

include_once LAYOUTS . "side.phtml";
include_once LAYOUTS . "footer_main.phtml";
