<div class="theme-box page-item profile-menu">
    <div class="main-title profile-menu-title"> searched text here </div>
    <div class="profile-section">
        <div class="profile-menu-desc">
            <b class="profile-menu-desc-key"> Results </b>
            <div class="profile-menu-desc-value float-right"> 100.1K </div>
        </div>
    </div>
    <div class="profile-menu-nav">
        <a class="profile-menu-nav-item" href="/?url=search/posts"> Posts </a>
        <a class="profile-menu-nav-item" href="/?url=search/users"> Users </a>
    </div>
</div>
