<?php
$title = "Settings";
include_once LAYOUTS . "header_wide.phtml"; ?>

<div class="theme-box settings-cont">
    <div class="main-title settings-text settings-section-title"> Appearance </div>
    <div class="settings-section">
        <div class="settings-item settings-piece">
            <div class="settings-item-key"> Light / Dark Theme </div>
            <div class="select storage{local:main-theme} dropdown settings-item-value position-right" tabindex="0">
                <div class="dropdown-btn"> <em class="select-checked"></em> &nbsp▼ </div>
                <ul class="dropdown-cont position-right">
                    <li class="select-item dropdown-item select{main-theme:dark} check{state:1}"> Dark </li>
                    <li class="select-item dropdown-item select{main-theme:light} check{state:0}"> Light </li>
                </ul>
            </div>
        </div>
        <div class="settings-item settings-piece">
            <div class="settings-item-key"> Color Theme </div>
            <div class="select storage{local:color-theme} dropdown settings-item-value position-right" tabindex="0">
                <div class="dropdown-btn"> <em class="select-checked"></em> &nbsp▼ </div>
                <ul class="dropdown-cont position-right">
                    <li class="select-item dropdown-item select{color-theme:red} check{state:0}"> Red </li>
                    <li class="select-item dropdown-item select{color-theme:green} check{state:0}"> Green </li>
                    <li class="select-item dropdown-item select{color-theme:blue} check{state:1}"> Blue </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="theme-box settings-cont">
    <div class="main-title settings-text settings-section-title"> User Information </div>
    <div class="settings-section settings-menu-section settings-piece">
        <div class="settings-menu-item">
            <div class="main-title"> Username </div>
            <input class="main-input settings-input" type="text">
        </div>
        <div class="settings-menu-item">
            <div class="main-title"> Email </div>
            <input class="main-input settings-input" type="email">
        </div>
    </div>
    <div class="main-title settings-text settings-section-title"> Password </div>
    <div class="settings-section settings-menu-section settings-piece">
        <div class="settings-menu-item">
            <div class="main-title"> Old Password </div>
            <input class="main-input settings-input" type="password">
        </div>
        <div class="settings-menu-item">
            <div class="main-title"> New Password </div>
            <input class="main-input settings-input" type="password">
        </div>
        <div class="settings-menu-item">
            <div class="main-title"> New Password (Repeat) </div>
            <input class="main-input settings-input" type="password">
        </div>
    </div>
    <button class="main-button block-right" type="submit" name="button"> Save Changes </button>
</div>
<div class="theme-box settings-cont">
    <div class="main-title settings-text settings-section-title"> Delete Account </div>
    <div class="settings-text">
        This action will delete your account, posts, comments, likes, votes
        and all other actions made by you, irreversably. Press the button bellow
        to send a verification to your email for deleting your account.
    </div>
    <button class="main-button block-right" type="submit" name="button"> Delete Account </button>
</div>

<?php include_once LAYOUTS . "footer_wide.phtml";
