<div class="theme-box page-item">
    <div class="media-bar">
        <div class="media-bar-item"> user_name </div>
        <div class="float-right">
            <div class="dropdown" tabindex="0">
                <div class="dropdown-btn"> ••• </div>
                <ul class="dropdown-cont position-right">
                    <li class="dropdown-item"> Delete </li>
                    <li class="dropdown-item"> Edit </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="media-cont">
        <div class="media-text post-title"> This is a title </div>
        <div class="media-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            nisi ut aliquip ex ea commodo consequat.
        </div>
        <div class="media-section">
            <div class="poll-bar-cont">
                <div class="poll-bar-amt"> 33% </div>
                <div class="poll-bar">
                    <div class="poll-voted"> Option 1 </div>
                </div>
            </div>
            <div class="poll-bar-cont">
                <div class="poll-bar-amt"> 33% </div>
                <div class="poll-bar">
                    <div class="poll-voted"> Option 2 </div>
                </div>
            </div>
            <div class="poll-bar-cont">
                <div class="poll-bar-amt"> 33% </div>
                <div class="poll-bar">
                    <div class="poll-voted"> Option 3 </div>
                </div>
            </div>
        </div>
    </div>
    <div class="media-bar">
        <div class="media-bar-item">
            <img class="invert-icon media-bar-icon" src="/img/icons/heart-icon.png">
            <div class="media-bar-icon-value"> 99 </div>
        </div>
        <div class="media-bar-item">
            <img class="invert-icon media-bar-icon" src="/img/icons/comm-icon.png">
            <div class="media-bar-icon-value"> 99 </div>
        </div>
        <div class="media-bar-item float-right">
            <img class="invert-icon media-bar-icon" src="/img/icons/share-icon.png">
        </div>
    </div>
</div>
