<div class="media post">
    <div class="media-bar">
        <a class="media-bar-item" href="/?url=user/posts"> user_name </a>
        <div class="float-right">
            <div class="dropdown" tabindex="0">
                <div class="dropdown-btn">•&nbsp•&nbsp•</div>
                <ul class="dropdown-cont position-right">
                    <li class="dropdown-item"> Delete </li>
                    <li class="dropdown-item"> Edit </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="media-cont">
        <div class="main-title media-text post-title"> This is a title </div>
        <div class="media-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            nisi ut aliquip ex ea commodo consequat.
        </div>
        <div class="poll-cont media-section">
            <div class="poll-bar-cont">
                <div class="float-right poll-bar-amt"> 33% </div>
                <div class="poll-bar" title="unchecked">
                    <div class="poll-bar-text"> Option 1 </div>
                    <div class="poll-voted"></div>
                </div>
            </div>
            <div class="poll-bar-cont">
                <div class="float-right poll-bar-amt"> 33% </div>
                <div class="poll-bar" title="unchecked">
                    <div class="poll-bar-text"> Option 2 </div>
                    <div class="poll-voted"></div>
                </div>
            </div>
            <div class="poll-bar-cont">
                <div class="float-right poll-bar-amt"> 33% </div>
                <div class="poll-bar" title="unchecked">
                    <div class="poll-bar-text"> Option 3 </div>
                    <div class="poll-voted"></div>
                </div>
            </div>
            <div class="media-info-text-cont">
                <div class="main-info-text"> 545 Votes </div>
                <div class="main-info-text"> Current Results </div>
            </div>
        </div>
    </div>
    <div class="media-date float-right"> 2015, 25 October </div>
    <div class="media-bar">
        <div class="media-bar-item media-bar-like">
            <img class="invert-icon media-bar-icon" src="/img/icons/heart-icon.png" title="unchecked">
            <div class="media-bar-icon-value"> 99 </div>
        </div>
        <a class="media-bar-item" href="/?url=post">
            <img class="invert-icon media-bar-icon" src="/img/icons/comm-icon.png">
            <div class="media-bar-icon-value"> 99 </div>
        </a>
        <div class="media-bar-item float-right">
            <img class="invert-icon media-bar-icon" src="/img/icons/share-icon.png">
        </div>
    </div>
</div>
