<div class="theme-box page-item profile-menu">
    <div class="profile-menu-back"></div>
    <img class="profile-menu-icon block-middle" src="/img/icons/profile-icon.png" alt="">
    <div class="profile-menu-title"> user_name </div>
    <div class="profile-section">
        <div class="profile-menu-desc">
            <img class="profile-menu-desc-icon invert-icon" src="/img/icons/cake-icon.png" alt="">
            <b class="profile-menu-desc-key"> Spawn </b>
            <div class="profile-menu-desc-value float-right"> 2015, 10 October </div>
        </div>
        <div class="profile-menu-desc">
            <img class="profile-menu-desc-icon invert-icon" src="/img/icons/heart-checked-icon.png" alt="">
            <b class="profile-menu-desc-key"> Likes </b>
            <div class="profile-menu-desc-value float-right"> 502 </div>
        </div>
        <div class="profile-menu-desc">
            <img class="profile-menu-desc-icon invert-icon" src="/img/icons/poll-icon.png" alt="">
            <b class="profile-menu-desc-key"> Votes </b>
            <div class="profile-menu-desc-value float-right"> 14.5K </div>
        </div>
    </div>
    <div class="profile-menu-nav">
        <a class="profile-menu-nav-item" href="/?url=user/posts"> Posts </a>
        <a class="profile-menu-nav-item" href="/?url=user/comments"> Comments </a>
    </div>
</div>
