            <div class="theme-box page-item info-side">
                <a class="info-side-text" href="#"> Facebook </a>
                <a class="info-side-text" href="#"> Instagram </a>
                <a class="info-side-text" href="#"> Twitter </a>
                <a class="info-side-text" href="#"> Youtube </a>
            </div>
            <div class="theme-box page-item info-side">
                <a class="info-side-text" href="#"> Privacy </a>
                <a class="info-side-text" href="#"> Help </a>
                <a class="info-side-text" href="#"> Advertise </a>
                <a class="info-side-text" href="#"> Terms </a>
                <a class="info-side-text" href="#"> Blog </a>
                <a class="info-side-text" href="#"> About </a>
            </div>
        </div>
    </main>
</body>

<script src="/script/main.js" charset="utf-8"></script>
</html>
