            <div class="theme-box info-side">
                <a class="info-side-text" href="#"> Privacy </a>
                <a class="info-side-text" href="#"> Help </a>
                <a class="info-side-text" href="#"> Advertise </a>
                <a class="info-side-text" href="#"> Terms </a>
                <a class="info-side-text" href="#"> Blog </a>
                <a class="info-side-text" href="#"> About </a>
            </div>
        </div>
    </main>
</body>
</html>
