<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title> Poller Bear <?php if (!empty($title)) echo "| $title" ?> </title>

    <link rel="stylesheet" href="/style/theme.css">
    <link rel="stylesheet" href="/style/main.css">
    <link rel="stylesheet" href="/style/dropdown.css">
    <link rel="stylesheet" href="/style/header.css">
    <link rel="stylesheet" href="/style/page.css">
    <link rel="stylesheet" href="/style/media_query.css">
    <link rel="stylesheet" href="/style/media.css">
    <link rel="stylesheet" href="/style/post.css">
    <link rel="stylesheet" href="/style/comment.css">
    <link rel="stylesheet" href="/style/poll.css">
</head>
<body>
    <header class="theme-box header-main">
        <a href="/" class="header-item">
            <img class="invert-icon header-logo" src="/img/icons/logo.png">
        </a>
        <input class="main-input header-input" name="" placeholder="search...">
        <div class="float-right">
            <?php if (empty($_SESSION["user_id"])) { ?>
                <div class="header-item"> Login </div>
            <?php } ?>
            <div class="dropdown" tabindex="0">
                <div class="dropdown-btn header-item"> ••• </div>
                <ul class="dropdown-cont position-right">
                    <li class="dropdown-item"> Settings </li>
                    <li class="dropdown-item"> About </li>
                    <?php if (!empty($_SESSION["user_id"])) { ?>
                        <div class="dropdown-item"> Logout </div>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </header>

    <main class="page-temp-main">
        <div class="page-main">
